name: l_alternative
description: "A mood tracking and mental wellness app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ^3.9.2
  flutter: 3.35.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.5.3
  flutter_staggered_grid_view: ^0.7.0
  monikode_event_store: ^2.2.1
  fl_chart: ^1.1.1
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1

  # Firebase packages
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0

  url_launcher: ^6.3.2
  http: ^1.6.0
  flutter_date_formatter: ^0.0.9
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/moods/
    - assets/images/plants/rose/
    - assets/images/avatars/
    - assets/fonts/

  fonts:
    - family: Chillax
      fonts:
        - asset: assets/fonts/Chillax/Chillax-Extralight.otf
          weight: 100
        - asset: assets/fonts/Chillax/Chillax-Light.otf
          weight: 300
        - asset: assets/fonts/Chillax/Chillax-Regular.otf
          weight: 400
        - asset: assets/fonts/Chillax/Chillax-Medium.otf
          weight: 500
        - asset: assets/fonts/Chillax/Chillax-Semibold.otf
          weight: 600
        - asset: assets/fonts/Chillax/Chillax-Bold.otf
          weight: 700
    - family: Inclusive Sans
      fonts:
        - asset: assets/fonts/InclusiveSans/InclusiveSans-Light.ttf
          weight: 300
        - asset: assets/fonts/InclusiveSans/InclusiveSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InclusiveSans/InclusiveSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InclusiveSans/InclusiveSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InclusiveSans/InclusiveSans-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#EAE3D9"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
